---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-app
  namespace: demo-app
  labels:
    app: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: helloworld
          image: atoonk/helloworld
