apiVersion: v1
kind: Service
metadata:
  namespace: demo-app
  annotations:
    mysocket.io/enabled: "true"
  labels:
    app: demo-app
    service: demo-service
  name: demo-service
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: demo-app
